// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// eth_int_capture //
// --------------- //

#define eth_int_capture_wrap_target 0
#define eth_int_capture_wrap 2
#define eth_int_capture_pio_version 0

static const uint16_t eth_int_capture_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0x2020, //  1: wait   0 pin, 0
    0xc001, //  2: irq    nowait 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program eth_int_capture_program = {
    .instructions = eth_int_capture_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = eth_int_capture_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config eth_int_capture_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + eth_int_capture_wrap_target, offset + eth_int_capture_wrap);
    return c;
}

static inline void eth_int_capture_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = eth_int_capture_program_get_default_config(offset);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    sm_config_set_in_pins(&c, pin);
    sm_config_set_clkdiv(&c, 1.0f);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

