// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// pps_capture //
// ----------- //

#define pps_capture_wrap_target 0
#define pps_capture_wrap 2
#define pps_capture_pio_version 0

static const uint16_t pps_capture_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0x20a0, //  1: wait   1 pin, 0
    0xc000, //  2: irq    nowait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pps_capture_program = {
    .instructions = pps_capture_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = pps_capture_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pps_capture_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pps_capture_wrap_target, offset + pps_capture_wrap);
    return c;
}

static inline void pps_capture_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = pps_capture_program_get_default_config(offset);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    sm_config_set_in_pins(&c, pin);
    sm_config_set_clkdiv(&c, 1.0f); // volle Systemfrequenz (150 MHz)
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

