// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// spi_cmd //
// ------- //

#define spi_cmd_wrap_target 0
#define spi_cmd_wrap 1
#define spi_cmd_pio_version 0

static const uint16_t spi_cmd_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1         side 0
    0xb042, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program spi_cmd_program = {
    .instructions = spi_cmd_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = spi_cmd_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config spi_cmd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spi_cmd_wrap_target, offset + spi_cmd_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void spi_cmd_init(PIO pio, uint sm, uint offset,
                                uint io0_pin, uint sclk_pin, float clkdiv) {
    pio_sm_config c = spi_cmd_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, sclk_pin);
    sm_config_set_out_pins(&c, io0_pin, 1);
    // MSB-first, autopull bei 8 Bit
    sm_config_set_out_shift(&c, false, true, 8);
    sm_config_set_clkdiv(&c, clkdiv);
    pio_gpio_init(pio, io0_pin);
    pio_gpio_init(pio, sclk_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, io0_pin, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, sclk_pin, 1, true);
    gpio_put(sclk_pin, 0); // SCLK idle LOW
    pio_sm_init(pio, sm, offset, &c);
}

#endif

// ---------- //
// qspi_write //
// ---------- //

#define qspi_write_wrap_target 0
#define qspi_write_wrap 1
#define qspi_write_pio_version 0

static const uint16_t qspi_write_program_instructions[] = {
            //     .wrap_target
    0x6004, //  0: out    pins, 4         side 0
    0xb042, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program qspi_write_program = {
    .instructions = qspi_write_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = qspi_write_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config qspi_write_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + qspi_write_wrap_target, offset + qspi_write_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void qspi_write_init(PIO pio, uint sm, uint offset,
                                   uint io0_pin, uint sclk_pin, float clkdiv) {
    pio_sm_config c = qspi_write_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, sclk_pin);
    sm_config_set_out_pins(&c, io0_pin, 4);
    // MSB-first, autopull bei 32 Bit (4 Bytes pro FIFO-Wort)
    sm_config_set_out_shift(&c, false, true, 32);
    sm_config_set_clkdiv(&c, clkdiv);
    for (int i = 0; i < 4; i++) pio_gpio_init(pio, io0_pin + i);
    pio_gpio_init(pio, sclk_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, sclk_pin, 1, true);
    // IO0-IO3 werden je nach Phase als Output/Input gesetzt
    pio_sm_init(pio, sm, offset, &c);
}

#endif

// --------- //
// qspi_read //
// --------- //

#define qspi_read_wrap_target 0
#define qspi_read_wrap 1
#define qspi_read_pio_version 0

static const uint16_t qspi_read_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop                    side 0
    0x5004, //  1: in     pins, 4         side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program qspi_read_program = {
    .instructions = qspi_read_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = qspi_read_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config qspi_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + qspi_read_wrap_target, offset + qspi_read_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void qspi_read_init(PIO pio, uint sm, uint offset,
                                  uint io0_pin, uint sclk_pin, float clkdiv) {
    pio_sm_config c = qspi_read_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, sclk_pin);
    sm_config_set_in_pins(&c, io0_pin);
    // MSB-first, autopush bei 32 Bit
    sm_config_set_in_shift(&c, false, true, 32);
    sm_config_set_clkdiv(&c, clkdiv);
    for (int i = 0; i < 4; i++) pio_gpio_init(pio, io0_pin + i);
    pio_gpio_init(pio, sclk_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, sclk_pin, 1, true);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

